import { ServiceCategory, FeatureControl, WalletTransaction, DiaryEntry } from './types';

export const INITIAL_SERVICES: ServiceCategory[] = [
  { id: 'mason', nameEn: 'Mason / Builder', nameTe: 'మేస్త్రీ', icon: '👷', available: true, basePrice: 800 },
  { id: 'plumber', nameEn: 'Plumber / Piping', nameTe: 'ప్లంబర్', icon: '🔧', available: true, basePrice: 350 },
  { id: 'electrician', nameEn: 'Electrician / Power', nameTe: 'ఎలక్ట్రీషియన్', icon: '⚡', available: true, basePrice: 400 },
  { id: 'painter', nameEn: 'Painter / Coloring', nameTe: 'పెయింటర్', icon: '🎨', available: true, basePrice: 500 },
  { id: 'welder', nameEn: 'Welder / Metal Work', nameTe: 'వెల్డర్', icon: '🔥', available: true, basePrice: 550 },
  { id: 'carpenter', nameEn: 'Carpenter / Wood Work', nameTe: 'కార్పెంటర్', icon: '🪚', available: true, basePrice: 450 },
  { id: 'tile_layer', nameEn: 'Tile Work / Flooring', nameTe: 'టైల్ పని', icon: '🧱', available: true, basePrice: 500 },
  { id: 'plastering', nameEn: 'Plastering / Masonry', nameTe: 'ప్లాస్టరింగ్', icon: '🏗️', available: true, basePrice: 600 },
  { id: 'roofing', nameEn: 'Roofing / Ceiling', nameTe: 'రూఫింగ్', icon: '🏠', available: true, basePrice: 600 },
  { id: 'flooring', nameEn: 'Flooring / Wood Board', nameTe: 'ఫ్లోరింగ్', icon: '🪵', available: true, basePrice: 550 },
  { id: 'gardener', nameEn: 'Garden / Landscaping', nameTe: 'గార్డెన్', icon: '🌿', available: true, basePrice: 350 },
  { id: 'decoration', nameEn: 'Decoration / Event Decor', nameTe: 'అలంకరణ', icon: '✨', available: true, basePrice: 1500 },
  { id: 'watertank', nameEn: 'Water Tank Repair', nameTe: 'నీటి ట్యాంక్', icon: '💧', available: true, basePrice: 300 },
  { id: 'sewage', nameEn: 'Sewage / Faucet / Pipe', nameTe: 'సీటేజి', icon: '🚰', available: true, basePrice: 350 },
  { id: 'gatework', nameEn: 'Gate Work / Fabrication', nameTe: 'గేట్ పని', icon: '🚪', available: true, basePrice: 450 },
  { id: 'grills', nameEn: 'Grills / Windows / Bolts', nameTe: 'గ్రిల్స్', icon: '🔩', available: true, basePrice: 450 },
  { id: 'glasswork', nameEn: 'Glass Work / Windows', nameTe: 'గ్లాస్ పని', icon: '🪟', available: true, basePrice: 450 },
  { id: 'powerwash', nameEn: 'Power Wash / Cleaning', nameTe: 'పవర్ వాష్', icon: '🚿', available: true, basePrice: 300 },
  { id: 'cleaner', nameEn: 'Cleaning / Housekeeping', nameTe: 'క్లీనింగ్', icon: '🧹', available: true, basePrice: 300 },
  { id: 'liftwork', nameEn: 'Lift Work / Elevator', nameTe: 'లిఫ్ట్ పని', icon: '🛗', available: true, basePrice: 800 },
  { id: 'ruler', nameEn: 'Draftsman / Surveyor', nameTe: 'రూలర్', icon: '📐', available: true, basePrice: 800 },
  { id: 'abacus', nameEn: 'Estimator / Billing', nameTe: 'అబాకస్', icon: '🧮', available: true, basePrice: 800 },
  { id: 'clipboard', nameEn: 'Supervisor / Checklist', nameTe: 'క్లిప్‌బోర్డ్', icon: '📋', available: true, basePrice: 800 },
  { id: 'gear', nameEn: 'Machinery Mechanic / Gear', nameTe: 'గేర్', icon: '⚙️', available: true, basePrice: 500 },
  { id: 'astrology', nameEn: 'Astrology / Calendar', nameTe: 'పంచాంగం', icon: '🕉️', available: true, basePrice: 200 },
  { id: 'biopower', nameEn: 'Bio-Power Manager', nameTe: 'బయో-పవర్', icon: '🔋', available: true, basePrice: 0 },
  { id: 'radio', nameEn: 'Offline Radio', nameTe: 'ఆఫ్‌లైన్ రేడియో', icon: '📡', available: true, basePrice: 0 },
  { id: 'ecommerce', nameEn: 'Local Mart / Shopping', nameTe: 'లోకల్ మార్ట్ / ఆన్‌లైన్ షాపింగ్', icon: '🛒', available: true, basePrice: 0 }
];

export const INITIAL_FEATURES: FeatureControl[] = [
  { id: 'feat_splash', nameEn: 'Animated Splash Screen', nameTe: 'మొదటి సినిమాటిక్ మెరుపు స్క్రీన్', state: 'perm_upgrade' },
  { id: 'feat_ecommerce', nameEn: 'Hyper-Local E-Commerce', nameTe: 'హైపర్-లోకల్ ఇ-కామర్స్', state: 'perm_upgrade' },
  { id: 'feat_attendance', nameEn: 'Worker Attendance Switch', nameTe: 'సింగిల్ యాప్ & హాజరు స్విచ్', state: 'perm_upgrade' },
  { id: 'feat_service_1', nameEn: '1. Mason / Builder Service', nameTe: '1. మేస్త్రీ కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_2', nameEn: '2. Plumber / Piping Service', nameTe: '2. ప్లంబర్ కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_3', nameEn: '3. Electrician / Power Service', nameTe: '3. ఎలక్ట్రీషియన్ కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_4', nameEn: '4. Painter / Coloring Service', nameTe: '4. పెయింటర్ కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_5', nameEn: '5. Welder / Metal Work Service', nameTe: '5. వెల్డర్ కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_6', nameEn: '6. Carpenter / Wood Work Service', nameTe: '6. కార్పెంటర్ కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_7', nameEn: '7. Tile Work / Flooring Service', nameTe: '7. టైల్ పని కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_8', nameEn: '8. Plastering / Masonry Service', nameTe: '8. ప్లాస్టరింగ్ కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_9', nameEn: '9. Roofing / Ceiling Service', nameTe: '9. రూఫింగ్ కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_10', nameEn: '10. Flooring / Wood Board Service', nameTe: '10. ఫ్లోరింగ్ కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_11', nameEn: '11. Garden / Landscaping Service', nameTe: '11. గార్డెన్ కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_12', nameEn: '12. Decoration / Event Decor Service', nameTe: '12. అలంకరణ కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_13', nameEn: '13. Water Tank Repair Service', nameTe: '13. నీటి ట్యాంక్ కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_14', nameEn: '14. Sewage / Faucet / Pipe Service', nameTe: '14. సీటేజి కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_15', nameEn: '15. Gate Work / Fabrication Service', nameTe: '15. గేట్ పని కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_16', nameEn: '16. Grills / Windows / Bolts Service', nameTe: '16. గ్రిల్స్ కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_17', nameEn: '17. Glass Work / Windows Service', nameTe: '17. గ్లాస్ పని కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_18', nameEn: '18. Power Wash / Cleaning Service', nameTe: '18. పవర్ వాష్ కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_19', nameEn: '19. Cleaning / Housekeeping Service', nameTe: '19. క్లీనింగ్ కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_20', nameEn: '20. Lift Work / Elevator Service', nameTe: '20. లిఫ్ట్ పని కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_21', nameEn: '21. Draftsman / Surveyor Service', nameTe: '21. రూలర్ కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_22', nameEn: '22. Estimator / Billing Service', nameTe: '22. అబాకస్ కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_23', nameEn: '23. Supervisor / Checklist Service', nameTe: '23. క్లిప్‌బోర్డ్ కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_24', nameEn: '24. Machinery Mechanic / Gear Service', nameTe: '24. గేర్ కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_25', nameEn: '25. Astrology / Calendar Service', nameTe: '25. పంచాంగం కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_26', nameEn: '26. Bio-Power Manager Service', nameTe: '26. బయో-పవర్ కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_27', nameEn: '27. Offline Radio Service', nameTe: '27. ఆఫ్‌లైన్ రేడియో కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_service_28', nameEn: '28. Local Mart / Shopping Service', nameTe: '28. లోకల్ మార్ట్ / ఆన్‌లైన్ షాపింగ్ కేటగిరీ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_calendar', nameEn: 'Scheduling Calendar UI', nameTe: 'షెడ్యూలింగ్ క్యా లెండర్ స్క్రీన్', state: 'perm_upgrade' },
  { id: 'feat_geofencing', nameEn: 'Dynamic KM Geofencing Map', nameTe: 'కిలోమీటర్ పరిధి జియోఫెన్సింగ్ మ్యాప్', state: 'perm_upgrade' },
  { id: 'feat_calling', nameEn: 'Direct Phone Intent Calling', nameTe: 'ఉచిత డైరెక్ట్ ఫోన్ కాల్', state: 'perm_upgrade' },
  { id: 'feat_sos', nameEn: 'SOS Emergency Tracker', nameTe: 'SOS అత్యవసర ట్రాకర్ బటన్', state: 'perm_upgrade' },
  { id: 'feat_kyc', nameEn: 'KYC & Identity Verification', nameTe: 'KYC & గూగుль వెరిఫికేషన్ స్క్రీన్', state: 'perm_upgrade' },
  { id: 'feat_wallet', nameEn: 'Worker Wallet Ledger', nameTe: 'వర్కర్ డిజిటల్ వాలెట్ బుక్', state: 'perm_upgrade' },
  { id: 'feat_ratings', nameEn: 'Star Rating & Feedback', nameTe: 'స్టార్ రేటింగ్ & ఫీడ్బ్యాక్ స్క్రీన్', state: 'perm_upgrade' },
  { id: 'feat_walkietalkie', nameEn: 'Gaming Walkie-Talkie', nameTe: 'గేమింగ్ శైలి వాకీ-టాకీ ప్రధాన బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_subscriptions', nameEn: 'Business Subscription Tiers', nameTe: 'బిజినెస్ సబ్స్క్రిప్షన్ ప్లాన్ కార్డులు', state: 'perm_upgrade' },
  { id: 'feat_diary', nameEn: 'Manual Payment Private Diary', nameTe: 'ఖర్చుల పర్సనల్ డిజిటల్ డైరీ', state: 'perm_upgrade' },
  { id: 'feat_social', nameEn: 'Social Media Hub & Shares', nameTe: 'సామాజిక మాధ్యమాల షేరింగ్ బోర్డు', state: 'perm_upgrade' },
  { id: 'feat_hybrid_radio', nameEn: 'Offline Radio Frequency', nameTe: 'ఆఫ్‌లైన్ రేడియో నెట్‌వర్క్', state: 'perm_upgrade' },
  // 11 Premium / Postpaid Features
  { id: 'feat_biopower', nameEn: 'Smart Bio-Power Manager', nameTe: 'స్మార్ట్ బయో-పవర్ మేనేజర్', state: 'perm_upgrade' },
  { id: 'feat_premium_assistant', nameEn: 'Advanced AI Assistant & Voice', nameTe: 'అడ్వాన్స్డ్ AI అసిస్టెంట్ & వాయిస్ కమాండ్స్', state: 'perm_upgrade' },
  { id: 'feat_premium_tracking', nameEn: 'Real-time Live Location Tracking', nameTe: 'రియల్ టైమ్ లైవ్ లొకేషన్ ట్రాకింగ్', state: 'perm_upgrade' },
  { id: 'feat_premium_radio', nameEn: 'Unlimited Range Walkie-Talkie', nameTe: 'అపరిమిత రేంజ్ వాకీ-టాకీ', state: 'perm_upgrade' },
  { id: 'feat_premium_invoicing', nameEn: 'Automated Quotation & GST Invoices', nameTe: 'ఆటోమేటిక్ కొటేషన్ & GST ఇన్‌వాయిస్', state: 'perm_upgrade' },
  { id: 'feat_premium_payments', nameEn: 'Zero Commission Online Payments', nameTe: 'జీరో కమిషన్ ఆన్‌లైన్ పేమెంట్స్', state: 'perm_upgrade' },
  { id: 'feat_premium_escrow', nameEn: 'Escrow Payment & Work Protection', nameTe: 'ఎస్క్రో పేమెంట్ సిస్టమ్ (సేఫ్ పేమెంట్)', state: 'perm_upgrade' },
  { id: 'feat_premium_multilingual', nameEn: 'Auto Translation Support', nameTe: 'ఆటోమేటిక్ భాషా అనువాదం', state: 'perm_upgrade' },
  { id: 'feat_premium_verification', nameEn: 'Premium Trust Badge Check', nameTe: 'ప్రీమియం ట్రస్ట్ బ్యాడ్జ్ (వెరిఫికేషన్)', state: 'perm_upgrade' },
  { id: 'feat_premium_support', nameEn: 'Priority 24/7 Dedicated Support', nameTe: '24/7 కస్టమర్ సపోర్ట్ టీమ్', state: 'perm_upgrade' },
  { id: 'feat_premium_analytics', nameEn: 'Advanced Business Analytics', nameTe: 'బిజినెస్ వర్క్ అనలిటిక్స్ & రిపోర్ట్స్', state: 'perm_upgrade' },
  { id: 'feat_premium_team', nameEn: 'Sub-worker / Team Management', nameTe: 'టీమ్/సబ్-వర్కర్ మేనేజ్‌మెంట్', state: 'perm_upgrade' },
  { id: 'feat_invoice_generator', nameEn: 'Invoice Generator & Postpaid Link', nameTe: 'ఇన్‌వాయిస్ జనరేటర్ & పోస్ట్‌పెయిడ్ లింక్', state: 'perm_upgrade' },
  { id: 'feat_profile_menu', nameEn: 'Hamburger Profile Menu', nameTe: 'ప్రొఫైల్ హ్యాంబర్గర్ మెనూ', state: 'perm_upgrade' },
  { id: 'feat_bp_sugar', nameEn: 'BP & Sugar Estimation', nameTe: 'రక్తపోటు & షుగర్ అంచనా', state: 'perm_upgrade' },
  { id: 'feat_doctor_scan', nameEn: 'AI Doctor Face Health Scanner', nameTe: 'AI డాక్టర్ ఫేస్ హెల్త్ స్కానర్', state: 'perm_upgrade' },
  { id: 'feat_weather_report', nameEn: 'RF Weather Radio Report', nameTe: 'వాతావరణ నివేదిక రేడియో బటన్', state: 'perm_upgrade' },
  { id: 'feat_invisible_maintenance', nameEn: 'Invisible Maintenance Assistant', nameTe: 'ఇన్విజిబుల్ మెయింటెనెన్స్ అసిస్టెంట్ (ఆటో-హీలింగ్)', state: 'perm_upgrade' },
  { id: 'feat_brahmastra', nameEn: 'Brahmastra Multi-Agent Control', nameTe: 'బ్రహ్మాస్త్ర మల్టీ-ఏజెంట్ కంట్రోల్ ప్యానెల్', state: 'perm_upgrade' },
];

export const INITIAL_WALLET_TRANSACTIONS: WalletTransaction[] = [
  { id: 't1', date: '2026-07-10', descriptionEn: 'Welcome Bonus Points Credit', descriptionTe: 'స్వాగత బోనస్ పాయింట్ల క్రెడిట్', points: 1000, type: 'credit' },
  { id: 't2', date: '2026-07-11', descriptionEn: 'Lead Approved Deduction - Plumber request', descriptionTe: 'లీడ్ ఆమోదించబడింది - ప్లంబర్ అభ్యర్థన', points: -50, type: 'debit' },
  { id: 't3', date: '2026-07-12', descriptionEn: 'Lead Approved Deduction - Electrician request', descriptionTe: 'లీడ్ ఆమోదించబడింది - ఎలక్ట్రీషియన్ అభ్యర్థన', points: -75, type: 'debit' },
];

export const INITIAL_DIARY_ENTRIES: DiaryEntry[] = [
  { id: 'd1', date: '2026-07-11', description: 'Plumbing repair work at Kukatpally client', amount: 850, type: 'income' },
  { id: 'd2', date: '2026-07-11', description: 'Bought PVC pipe fitting materials', amount: 150, type: 'expense' },
  { id: 'd3', date: '2026-07-12', description: 'Electrical wire fixing at Gachibowli villa', amount: 1200, type: 'income' },
  { id: 'd4', date: '2026-07-13', description: 'Auto travel fare charges', amount: 180, type: 'expense' },
];
